console.error(HALP!)
console.log("I would be a logger")
console.log('log')
console.log()
console.log.restore()
console.log(restore)
console.log(node_modules/expect/lib/Expectation.js:318:28)
console.log(done)
console.log('done')
